### ISSUE TITLE
"Size Based PRE" optimization error

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#15]
Hello.

I think, version `2.0.79` has serious problem with "Size Based PRE" optimization enabled for some cases.

Function
```monkey-c
function f(x as Number) as Number {
    var y = x * x;
    y *= y;
    return y + y;
}
```
got optimized to
```monkey-c
function f(x as Number) as Number {
    x /*>y<*/ = x * x;
    return x /*>y<*/ + x /*>y<*/;
}
```
and returns wrong value as `y *= y` expression is missing.

Plugin settings have default values except for `"prettierMonkeyC.checkCompilerLookupRules": "OFF",`.

Could you, please, fix this?

Thanks.

**Comment by markw65** [comment]
Looking at it now.
