### ISSUE TITLE
pmc-analysis thinks the "next" type of variable is already in the current line

### ISSUE THREAD

**Issue by flocsy** [markw65/monkeyc-optimizer#18]
```
import Toybox.Lang;
import Toybox.System;

class Foo {
    var mBlink as Number = 0;
    function bar() as Void {
        var blink = mBlink;
        mBlink = blink + 1;
        var two = 2;
        var blink = blink % two == 0;
        System.println(blink ? "BLINK" : "blink");
    }
}

```
Unexpected types for operator '%': [Null or Boolean or Float or Double or Char or String or Array or Dictionary or Method or Module or Function or Class or Object or Enum or Symbol or Typedef vs Number][pmc-analysis]
(on line: var blink = blink % two == 0;)

Previously I had a new variable introduced in that line but then I "manually optimized" and reused blink as it wasn't needed any more, and this broke the PMC

**Comment by markw65** [comment]
You have two variables named "blink" in the same block. Garmin would report that as an error. My optimizer renames the second one (because that's effectively what Garmin's compiler used to do, a long time ago), so your code becomes
```
    function bar() as Void {
        var blink = mBlink;
        mBlink = blink + 1;
        var two = 2;
        var blink2 = blink2 % two == 0;
        System.println(blink ? "BLINK" : "blink");
    }
```
And so now blink2 is uninitialized, and the error message is correct.

**Comment by flocsy** [comment]
Ah sorry, you're right, I forgot to remove the var before the "2nd" blink
