### ISSUE TITLE
ERROR: Internal: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ro8inmorgan** [markw65/monkeyc-optimizer#19]
If you :inline a very large function eventually you will get maximum call stack size exceeded. 

You should wrap this function in another function to give nodejs some chance to clear the call stick before moving into the the next iteration. Could you please have a look at this?

**Comment by markw65** [comment]
> You should wrap this function in another function to give nodejs some chance to clear the call stick before moving into the the next iteration

Which function are you referring to? Also, I can't really see how wrapping it in another function call will help reduce the call stack - unless you mean move it into an async function call; in which case, I don't think that's likely to be doable - I've already experimented a bit with that, and rewriting the optimizer to be async is a huge undertaking.

But if you can provide a test case, I'll take a look.

**Comment by markw65** [comment]
Without a test case, I'm going to close this as won't fix.
