### ISSUE TITLE
misleading warning: This function can only be inlined in statement, assignment, if or return contexts

### ISSUE THREAD

**Issue by flocsy** [markw65/monkeyc-optimizer#21]
```
if (self.someBoolean && foo(word)) {
  ...
}

(:inline)
function foo(word as String) as Boolean {
  ...
}

```
Gives a warning:
While inlining hasRepeatingLetters: This function can only be inlined in statement, assignment, if or return contexts

However switching the order works:
if (foo(word) && self.someBoolean)

I understand that there's a difference, because in the original order foo isn't called when someBoolean is false (that's why I wrote it in that order), but IMHO the warning message is misleading, because changing the order didn't change anything about the context IMHO.

**Comment by markw65** [comment]
This is as [documented here](https://github.com/markw65/monkeyc-optimizer/wiki/Inlining)

**Comment by flocsy** [comment]
Ok, so maybe give some hint in the warning message :)
Or if that's too complicated then maybe put there the link to the documentation.

The documentation's last sentence is "what went wrong", and you could argue if "This function can only be inlined in statement, assignment, if or return contexts" explains what went wrong or not. In my opinion it could be improved. And I am strictly talking about the warning message, not what an or can't be inlined. If the message could hint in some useful way what the developer can do to make it inlinable it could be great.

**Comment by markw65** [comment]
edfa0f47ba45acde17f6446b4b5a71ecaacc70d8 adds a [link to the context descriptions on the wiki page](https://github.com/markw65/monkeyc-optimizer/wiki/Inlining#so-inlining-is-restricted-to-a-few-fairly-common-places-or-contexts) to the diagnostic.
