### ISSUE TITLE
Wrong PRG file name is used for running optimized build

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#33]
If Monkey C project is added to VSCode as a part of workspace and has name that is different from the project's folder name, error "The provided PRG file does not exist" occurs during launch.
```
The provided PRG file does not exist: .../TestProject/bin/optimized-MyTestProject.prg
The provided source file does not exist: .../TestProject/bin/optimized-MyTestProject.prg.debug.xml
```

VSCode workspace file looks like
```json
{
    "folders": [
        {
            "name": "MyTestProject",
            "path": ".../TestProject"
        }
    ]
}
```

`monkeyc` successfully creates `bin/optimized-TestProject.prg` and `bin/optimized-TestProject.prg.debug.xml` files, that can be manually run by `monkeydo` without issues.

Thank you very much for the recent fixes! All my projects are now shining with "Build completed successfully".

**Comment by markw65** [comment]
Fixed by https://github.com/markw65/prettier-extension-monkeyc/commit/9fe6ea019f736cf85e670fcf82a966bd30ac9e6e
