### ISSUE TITLE
"Undefined symbol" for typedef as interface with parametrized function with enabled type check

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#36]
```monkey-c
import Toybox.Lang;

class Test {
    typedef TestType as interface {
    // Undefined symbol x
    function f(x as Number) as Void;
};
}
```

Also indentation level inside interface's curly braces seems incorrect after code formatting.

**Comment by markw65** [comment]
Fixed by 82d7a44bef38efdeccc459669f02adeb88d84a52 (and [c619406416](https://github.com/markw65/prettier-plugin-monkeyc/commit/c6194064164e47e09538a949657a67b6749fb936) for the indentation)
